### ISSUE TITLE
Credential Leak

### ISSUE THREAD

**Issue by MuhammetBurakGolec** [acikkaynak/ben-iyiyim#19]
Merhaba,
Gizli Anahtarların Açık Olması Olası oluşturulan herhangi bir şifrelemenin kırılmasında kullanla bilir. Django gizli anahtarlarını güvenli bir şekilde saklamak için aşağıdaki yolları kullanabilirsiniz:

1. Django gizli anahtarlarını bir dış kaynakta saklamaya yarayan `os` modülünü kullanma: Bu, gizli anahtarlarınızı uygulamanızın dışında tutmanızı ve güncellemenizi kolaylaştırır.

2. Django ortam değişkenlerini kullanma: Bu, gizli anahtarlarınızı uygulamanızın dışında tutmanızı ve yapılandırmanızı daha da kolaylaştırır.

3. Django gizli anahtarlarını bir dosya içinde saklamaya yarayan `python-decouple` paketini kullanma: Bu, gizli anahtarlarınızı uygulamanızın dışında tutmanızı ve güncellemenizi kolaylaştırır.

Her bir yolun avantajları ve dezavantajları vardır, bu nedenle en uygun yolu seçmek size bağlıdır. 

Umarım bu fikirler yardımcı olur.

MBG

https://github.com/acikkaynak/ben-iyiyim/blob/4adb19969f238dc662b17b34e8e43d6d9e85d117/.envs/.production/.django#LL5-L6C51

**Comment by argonft** [comment]
O branchteki kodlar kullanılmayacak. Teşekkürler kontrol ettiğiniz için.
