### ISSUE TITLE
Credential Leak

### ISSUE THREAD

**Issue by MuhammetBurakGolec** [acikkaynak/ben-iyiyim#20]
Merhaba,
Gizli Anahtarların Açık Olması Olası oluşturulan herhangi bir şifrelemenin kırılmasında kullanla bilir. Django gizli anahtarlarını güvenli bir şekilde saklamak için aşağıdaki yolları kullanabilirsiniz:

Django gizli anahtarlarını bir dış kaynakta saklamaya yarayan os modülünü kullanma: Bu, gizli anahtarlarınızı uygulamanızın dışında tutmanızı ve güncellemenizi kolaylaştırır.

Django ortam değişkenlerini kullanma: Bu, gizli anahtarlarınızı uygulamanızın dışında tutmanızı ve yapılandırmanızı daha da kolaylaştırır.

Django gizli anahtarlarını bir dosya içinde saklamaya yarayan python-decouple paketini kullanma: Bu, gizli anahtarlarınızı uygulamanızın dışında tutmanızı ve güncellemenizi kolaylaştırır.

Her bir yolun avantajları ve dezavantajları vardır, bu nedenle en uygun yolu seçmek size bağlıdır.

Umarım bu fikirler yardımcı olur.

MBG

https://github.com/acikkaynak/ben-iyiyim/blob/64789488bf99e7580ddc0f4df6a2c383d14d95e7/config/settings/local.py#L11

**Comment by argonft** [comment]
O branchteki kodlar kullanılmayacak. Teşekkürler kontrol ettiğiniz için.
