### ISSUE TITLE
Bu proje django'dan devam mı edecek?

### ISSUE THREAD

**Issue by yamac-kurtulus** [acikkaynak/ben-iyiyim#45]
Selam, 
Bu proje django'dan devam mı edecek, go'ya mı geçilecek? Django kalırsa yardımcı olabilirim, tech stack'im bir türlü align olmadı diğer projelerle :/

**Comment by argonft** [comment]
Selam, evet proje django kullanılarak yapıldı ve değiştirilmesi düşünülmüyor. Yapılacak bir şey kalmadı ama ileride yardımcı olmak isterseniz discorddan veya buradan takip edebilirsiniz.
